apiVersion: batch/v1
kind: Job
metadata:
  name: api-deployment
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      name: api-deployment
    spec:
      restartPolicy: OnFailure
      containers:
      - name: api
        image: 211104/api:v-daa4f13
        command: ["php",  "artisan", "migrate"]
  backoffLimit: 2