apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: api
          image: 211104/api:v-98b31476
          command: ['php', 'artisan', 'migrate']
      restartPolicy: OnFailure
  backoffLimit: 5
