apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: api
        image: 211104/api:v-0b218ac
        command: ["php",  "artisan", "migrate"]
      restartPolicy: Never
  backoffLimit: 4