apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/www/html/public/files